version: "3"
services: 
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: python -u app/main.py
        image: soccerstat_app
        restart: always
        container_name: app_container
        ports:
            - "5000:5000"
        volumes:
            - volume_app:/app
        networks: 
            - backend_net
        depends_on: 
            - backend

    backend:
        image: mongo:latest
        container_name: mongo_container
        hostname: soccerstat_mongodb
        restart: always
        environment:
            - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
        volumes:
            - volume_backend_db:/data/db
            - volume_backend_config:/data/configdb
        ports:
            - 27017:27017
        networks: 
            - backend_net
volumes: 
    volume_app:
        driver: local
    volume_backend_db:
        driver: local
    volume_backend_config:
        driver: local
networks: 
    backend_net:
        driver: bridge